services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  StudioMitte\Brevo\Command\TestCommand:
    tags:
      - name: 'console.command'
        command: 'brevo:test'
        schedulable: false

  StudioMitte\Brevo\Report\IntegrationReport:
    tags:
      - name: reports.report
